name: Deploy examples

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  compile-ui:
    uses: ./.github/workflows/compile-ui.yml
    with:
      artifact-name: spark-board-ui

  Build:
    runs-on: ubuntu-22.04
    needs: compile-ui
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre default-jdk

        pip install pipenv==2023.4.29
        pipenv sync

    # now collect the compiled UI from the previous job and insert it into the package
    - name: Download compiled UI
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.compile-ui.outputs.artifact-name }}
        path: spark_board/ui  # copy to the package's ui folder

    - name: Build examples
      run: |
        pipenv run python ./scripts/build_examples.py --output ./examples

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: page
        path: ./examples
        if-no-files-found: error
    
  Deploy:
    runs-on: ubuntu-22.04
    needs: Build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Collect artifacts
      uses: actions/download-artifact@v3
      with:
        name: page
        path: ./examples

    - name: Setup pages
      uses: actions/configure-pages@v1

    - name: Upload artifacts to pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./examples

    - name: Deploy examples to pages
      id: deployment
      uses: actions/deploy-pages@v2
