# IMPORTANT: to trigger a deploy you have to create a new release in github.
#            before creating the release, make sure to update the version in setup.py

name: Deploy spark-board package

on:
  release:
    types:
      - created

jobs:
  compile-ui:
    uses: ./.github/workflows/compile-ui.yml
    with:
      artifact-name: spark-board-ui

  # build the Python package and upload it to pypi
  Deploy:
    runs-on: ubuntu-22.04
    needs: compile-ui
    strategy:
      max-parallel: 5

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade twine
          python3 -m pip install --upgrade build

      - name: Process README
        run: |
          # overwrite the README.md with the rendered version
          REL_LINKS_BASE=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${GITHUB_REF_NAME}/
          python3 ./scripts/readme_renderer.py --file ./README.md --rel-links-base "$REL_LINKS_BASE" --output ./README.md

      # now collect the compiled UI from the previous job and insert it into the package
      - name: Download compiled UI
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.compile-ui.outputs.artifact-name }}
          path: spark_board/ui  # copy to the package's ui folder

      - name: Build dist
        run: python3 -m build

      # this step does not use any credentials because this repo is added as a trusted publisher
      # see https://docs.pypi.org/trusted-publishers/using-a-publisher/ for more information
      - name: Upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
